# Generated by Django 4.2.1 on 2023-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('ingredient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('recipe_card', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tite', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('preptime', models.CharField(max_length=100)),
                ('cooktime', models.CharField(max_length=100)),
                ('totaltime', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('servings', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
    ]
