# Generated by Django 4.2.1 on 2023-05-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recipe_shortcut',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='title',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_card',
        ),
        migrations.RemoveField(
            model_name='recipe_card',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='recipe_card',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe_card',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='recipe_card',
            name='region',
        ),
        migrations.RemoveField(
            model_name='recipe_card',
            name='tite',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='myfk2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='recipe_card',
            name='myfk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ratings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='recipe_card',
            name='instructions',
            field=models.TextField(),
        ),
    ]
