# Generated by Django 4.2.1 on 2023-05-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_recipe_shortcut_remove_ingredients_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_card',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ingredients',
        ),
    ]
